<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mdl-button__ripple-contai_1</name>
   <tag></tag>
   <elementGuidId>b64b123c-c008-40ea-809e-1f334bdd99db</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-button__ripple-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appWindow&quot;)/div[1]/div[@class=&quot;mdl-card__actions right&quot;]/button[@class=&quot;mdl-button mdl-js-button mdl-js-ripple-effect btn-accent-9 js-submit&quot;]/span[@class=&quot;mdl-button__ripple-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
