<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobilenum_dropdown</name>
   <tag></tag>
   <elementGuidId>956f09b6-6b63-4912-8e9c-9176e0afebf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;formCreateContact&quot;)/div[@class=&quot;form-control-group&quot;]/div[@class=&quot;form-control&quot;]/div[@class=&quot;mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-upgraded&quot;]/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/div[@class=&quot;selected-flag&quot;][count(. | //div[@class = 'selected-flag' and @tabindex = '0' and @title = 'United States: +1']) = count(//div[@class = 'selected-flag' and @tabindex = '0' and @title = 'United States: +1'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-flag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>United States: +1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCreateContact&quot;)/div[@class=&quot;form-control-group&quot;]/div[@class=&quot;form-control&quot;]/div[@class=&quot;mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-upgraded&quot;]/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/div[@class=&quot;selected-flag&quot;]</value>
   </webElementProperties>
</WebElementEntity>
