<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-arrow-right</name>
   <tag></tag>
   <elementGuidId>1e4045c3-212d-49c2-8644-094b0fd79769</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateUpdatePrivateLeadQualification&quot;)/div[@class=&quot;stepper__content is-active&quot;]/div[@class=&quot;form__section form__section--bg form__section--wide-padding mdl-shadow--2dp&quot;]/div[@class=&quot;form__actions form__actions--stepper&quot;]/button[@class=&quot;button-step button-step--next js-step-next&quot;]/i[@class=&quot;icon-arrow-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
