<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Albania</name>
   <tag></tag>
   <elementGuidId>ea0820f9-cbd0-4f90-99fc-dca78a15f1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>&quot;(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[2]/following::span[1]&quot;[count(. | //span[@data-value = 'AL' and @role = 'option' and @unselectable = 'on' and @class = ' e-ddltxt' and (text() = 'Albania' or . = 'Albania')]) = count(//span[@data-value = 'AL' and @role = 'option' and @unselectable = 'on' and @class = ' e-ddltxt' and (text() = 'Albania' or . = 'Albania')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>AL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> e-ddltxt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Albania</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>&quot;(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[2]/following::span[1]&quot;</value>
   </webElementProperties>
</WebElementEntity>
