<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-arrow-right_1</name>
   <tag></tag>
   <elementGuidId>0b96664e-5441-437f-a3a6-734645af8da3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form0&quot;)/div[@class=&quot;stepper__content is-active&quot;]/div[@class=&quot;form__section form__section--bg form__section--no-padding mdl-shadow--2dp&quot;]/div[@class=&quot;form__actions form__actions--stepper&quot;]/button[@class=&quot;button-step button-step--next js-step-next&quot;]/i[@class=&quot;icon-arrow-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
