<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Yes</name>
   <tag></tag>
   <elementGuidId>78e4c2ce-4e91-48f5-a32b-85e3a7137eca</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>pmsRequested-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-pms&quot;)/div[@class=&quot;form-control full-width&quot;]/div[@class=&quot;radio-menu-container radio-menu-container--label-top&quot;]/ul[@class=&quot;mdl-menu radio-menu-list radio-menu-list--horizontal radio-menu-list--flex-start&quot;]/li[@class=&quot;mdl-menu__item mdl-menu__item--min-width&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
