<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AgentLead_Editbtn</name>
   <tag></tag>
   <elementGuidId>3aeb2a29-5c02-43bc-9601-af2264abc7b4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-button__ripple-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AjaxBody&quot;)/div[@class=&quot;enquiry-detail&quot;]/div[@class=&quot;enquiry-detail__content&quot;]/div[@class=&quot;enquiry-detail__action is-sticky&quot;]/ul[@class=&quot;action-list&quot;]/li[@class=&quot;action-list__item&quot;]/a[@class=&quot;mdl-button action-list-button mdl-js-button mdl-js-ripple-effect lowercase btn-edition lead-edition&quot;]/span[@class=&quot;mdl-button__ripple-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
