<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Button</name>
   <tag></tag>
   <elementGuidId>fa68e035-4338-41ae-9db8-858646444380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = '//*[@id=&quot;AjaxBody&quot;]/div/div[1]/div/a[1]/span[2]' and @id = 'leadStatusButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>//*[@id=&quot;AjaxBody&quot;]/div/div[1]/div/a[1]/span[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leadStatusButton</value>
   </webElementProperties>
</WebElementEntity>
