<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PMS</name>
   <tag></tag>
   <elementGuidId>331215c4-a0c5-4d99-8050-0390a3547e2d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-step__text-main</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PMS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCreateUpdatePrivateLeadQualification&quot;)/div[@class=&quot;stepper__content is-active&quot;]/div[@class=&quot;form__section form__section--bg form__section--wide-padding mdl-shadow--2dp&quot;]/div[@class=&quot;form__actions form__actions--stepper&quot;]/button[@class=&quot;button-step button-step--next js-step-next&quot;]/span[@class=&quot;button-step__text&quot;]/span[@class=&quot;button-step__text-main&quot;]</value>
   </webElementProperties>
</WebElementEntity>
