<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VolumeWeight_DropDown</name>
   <tag></tag>
   <elementGuidId>b340c8c1-044f-430c-a1d1-a5517fa458b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>airUnitsVolumeWeightSelected_dropdown</value>
   </webElementProperties>
</WebElementEntity>
