<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Transfer_Submit</name>
   <tag></tag>
   <elementGuidId>c6529ce9-d822-4e88-9383-1be113002885</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-button mdl-js-button mdl-js-ripple-effect btn-accent-9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Submit
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferDialogContents_wrapper&quot;)/div[@class=&quot;e-dialog-scroller e-scroller e-js e-widget&quot;]/div[@id=&quot;transferDialogContents&quot;]/div[@class=&quot;mdl-card custom-card popup-card js-popup-card&quot;]/form[@id=&quot;formInternetTransferPopup&quot;]/div[@class=&quot;mdl-card__actions right&quot;]/button[@class=&quot;mdl-button mdl-js-button mdl-js-ripple-effect btn-accent-9&quot;]</value>
   </webElementProperties>
</WebElementEntity>
