<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1Customer</name>
   <tag></tag>
   <elementGuidId>99f850dc-c6a1-4596-b815-e2f274acb1dc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-arrow-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AjaxBody&quot;)/div[@class=&quot;dashboard-lead-creation&quot;]/div[@class=&quot;mdl-card custom-card custom-card--bordered mdl-shadow--2dp&quot;]/div[@class=&quot;mdl-card__supporting-text&quot;]/div[@class=&quot;table-wrapper&quot;]/table[@class=&quot;mdl-data-table mdl-js-data-table&quot;]/tbody[1]/tr[1]/td[7]/a[@id=&quot;showClient&quot;]/i[@class=&quot;icon-arrow-right&quot;]</value>
   </webElementProperties>
</WebElementEntity>
