<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>191eed3e-0302-4ab8-960d-4f8aafd2818c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdl-button mdl-js-button mdl-js-ripple-effect btn-accent-9 js-submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Submit
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;abandonDialogContents_wrapper&quot;)/div[@class=&quot;e-dialog-scroller e-scroller e-js e-widget&quot;]/div[@id=&quot;abandonDialogContents&quot;]/div[@class=&quot;mdl-card custom-card popup-card&quot;]/form[@id=&quot;form0&quot;]/div[@class=&quot;mdl-card__actions right&quot;]/button[@class=&quot;mdl-button mdl-js-button mdl-js-ripple-effect btn-accent-9 js-submit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
